name: CICD-Deploy_on_Heroku

on:
  push:
    branches:
      - master
      - main

jobs:
  myCI:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Your ML workflow goes here
        apt-get update && apt-get install -y
        apt-get install -y \
        python3 \
        python3-pip
        pip3 install --upgrade pip
        pip install -r requirements.txt
        echo "## HELLO"
        
  my_CD:
    runs-on: ubuntu-latest
    needs: [myCI]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-app-malaria" #Must be unique in Heroku
          heroku_email: "mkbensmaia@gmail.com"
          usedocker: true